services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: bancrot
      POSTGRES_USER: bot
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data 

volumes:
  pgdata:
networks:
  app_network:
    driver: bridge