"""add_privacy_consent_fields

Revision ID: 097113e3a958
Revises: dff2b87e4ff3
Create Date: 2025-06-11 17:20:57.071414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '097113e3a958'
down_revision: Union[str, None] = 'dff2b87e4ff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tel_users', sa.Column('privacy_accepted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tel_users', 'privacy_accepted')
    # ### end Alembic commands ###
