"""add new column to user

Revision ID: 25dbdbf7eb27
Revises: e3ce3e98f9bc
Create Date: 2025-04-17 14:39:36.138306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25dbdbf7eb27'
down_revision: Union[str, None] = 'e3ce3e98f9bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tel_users', sa.Column('activate_free_sub', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tel_users', 'activate_free_sub')
    # ### end Alembic commands ###
