"""add new column user fccp

Revision ID: 76f96191d829
Revises: 1221757391e9
Create Date: 2025-06-19 23:35:17.010720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76f96191d829'
down_revision: Union[str, None] = '1221757391e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tel_users', sa.Column('can_use_fccp', sa.Boolean(), nullable=False,server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tel_users', 'can_use_fccp')
    # ### end Alembic commands ###
